### ISSUE TITLE
Random crashes while idle

### ISSUE THREAD

**Issue by jeajones** [RUGSoftEng/2017-Cognitive-Sensors#108]
We need to figure out what is causing these issues as it's currently really difficult to stimulate in an emulator

**Comment by spina-a-d** [comment]
So this is 100% an issue with when the app connects to wifi, cause I get it on every wifi change and is clearly an issue introduced by something that was changed or added with the DB or wifi connector.  Can we please have this fixed and pushed to the Play Store soon because the professor has DLed our app in will keep getting these crash notifications.  @aukeroorda @LorenaArquero @jeajones

**Comment by aukeroorda** [comment]
Fixed in commit 5fc0d56
